admin_jobeet_home:
  path: /affiliates
  controller: App\JobeetModule\Admin\Actions\AffiliateManageAction:list

admin_jobeet_affiliate_create:
  path: /affiliates/new
  controller: App\JobeetModule\Admin\Actions\AffiliateManageAction:create
  methods: ['GET', 'POST']

admin_jobeet_affiliate_activate:
  path: /affiliates/activate/{id}
  controller: App\JobeetModule\Admin\Actions\AffiliateManageAction:activate
  methods: ['POST']
  requirements:
    id: '\d+'

admin_jobeet_affiliate_edit:
  path: /affiliates/edit/{id}
  controller: App\JobeetModule\Admin\Actions\AffiliateManageAction:edit
  methods: ['GET', 'POST']
  requirements:
    id: '\d+'

admin_jobeet_affiliate_delete:
  path: /affiliates/delete/{id}
  controller: App\JobeetModule\Admin\Actions\AffiliateManageAction:delete
  methods: ['DELETE']
  requirements:
    id: '\d+'
