admin_jobeet_home:
  path: /affiliates
  controller: App\AdminModule\Actions\Jobeet\AffiliateManageAction:list

admin_jobeet_affiliate_create:
  path: /affiliates/new
  controller: App\AdminModule\Actions\Jobeet\AffiliateManageAction:create
  methods: ['GET', 'POST']

admin_jobeet_affiliate_activate:
  path: /affiliates/activate/{id}
  controller: App\AdminModule\Actions\Jobeet\AffiliateManageAction:activate
  methods: ['POST']
  requirements:
    id: '\d+'

admin_jobeet_affiliate_edit:
  path: /affiliates/edit/{id}
  controller: App\AdminModule\Actions\Jobeet\AffiliateManageAction:edit
  methods: ['GET', 'POST']
  requirements:
    id: '\d+'

admin_jobeet_affiliate_delete:
  path: /affiliates/delete/{id}
  controller: App\AdminModule\Actions\Jobeet\AffiliateManageAction:delete
  methods: ['DELETE']
  requirements:
    id: '\d+'
