modules: 
  - App\Blog\BlogModule
  - App\Api\ApiModule

providers:
  - Simplex\Routing\RoutingServiceProvider
  - Simplex\Renderer\TwigServiceProvider

middlewares:
  global: 
    - Simplex\Middleware\TrailingSlashMiddleware
    - Simplex\Middleware\RoutingMiddleware
  groups:
    web: []
    api: []

database:
  type: sqlite
  name: database.db
  
