env: debug
app_host: simplex.io
modules:
  - App\Auth\AuthModule
  - App\Blog\BlogModule
  - App\JobeetModule\JobeetServiceProvider
  - App\AdminModule\AdminModuleProvider

providers:
  - Simplex\Routing\RoutingServiceProvider
  - Simplex\Database\DatabaseServiceProvider
  - Simplex\Http\Session\SessionServiceProvider
  - Simplex\Renderer\TwigServiceProvider
  - Simplex\Validation\ValidationServiceProvider
  - Simplex\DataMapper\DataMapperServiceProvider
  - Simplex\Security\Authentication\AuthenticationServiceProvider

twig:
  path: '%resources%/views'
  file_ext: twig
  extensions:
    - Simplex\Routing\Extensions\TwigRouterExtension
    - Simplex\Security\Csrf\TwigCsrfExtension
    - Simplex\Renderer\TwigFormExtension
    - Simplex\Security\Authentication\TwigAuthExtension

routing:
  strategies:
    web: Simplex\Middleware\WebMiddleware

  middlewares:
    global:
      - Simplex\Middleware\RoutingMiddleware
    web:
      - Simplex\Middleware\ErrorHandlerMiddleware
      - Simplex\Middleware\TrailingSlashMiddleware
      #- Simplex\Middleware\OverrideRequestMethodMiddleware
      - Simplex\Middleware\ValidationErrorsMiddleware
      - Simplex\Middleware\AddCookiesToResponseMiddleware
      - Simplex\Http\Session\SessionMiddleware
      - Simplex\Middleware\CsrfTokenMiddleware
      - Simplex\Middleware\TwigSessionMiddleware
    api: []

database:
  default: sqlite
  connections:
    sqlite:
      type: sqlite
      database: '%resources%/db/database.db'

auth:
  login_field: email
