env: debug
app_host: simplex.io
modules:
  - App\Auth\AuthModule
  - App\Blog\BlogModule
  - App\JobeetModule\JobeetServiceProvider
  - App\AdminModule\AdminModuleProvider

providers:
  - Simplex\Routing\RoutingServiceProvider
  - Simplex\Database\DatabaseServiceProvider
  - Simplex\Http\Session\SessionServiceProvider
  - Simplex\Renderer\TwigServiceProvider
  - Simplex\Validation\ValidationServiceProvider
  - Simplex\DataMapper\DataMapperServiceProvider
  - Simplex\Security\Authentication\AuthenticationServiceProvider
  - Simplex\Module\ModuleServiceProvider

twig:
  path: '%resources%/views'
  file_ext: twig
  extensions:
    - Simplex\Routing\Extensions\TwigRouterExtension
    - Simplex\Security\Csrf\TwigCsrfExtension
    - Simplex\Renderer\TwigFormExtension
    - Simplex\Security\Authentication\TwigAuthExtension

routing:
  strategies:
    web: Simplex\Strategy\WebStrategy
    api: Simplex\Strategy\ApiStrategy

  middlewares:
    global:
      - Simplex\Middleware\ErrorHandlerMiddleware
      - Simplex\Middleware\RoutingMiddleware
    web:
      - Simplex\Middleware\TrailingSlashMiddleware
      - Simplex\Middleware\ValidationErrorsMiddleware
      - Simplex\Middleware\AddCookiesToResponseMiddleware
      - Simplex\Http\Session\SessionMiddleware
      - Simplex\Middleware\CsrfTokenMiddleware
      - Simplex\Middleware\TwigSessionMiddleware
    api:
      - Simplex\Middleware\ApiTokenAuthenticationMiddleware
      - Simplex\Middleware\ParseJsonRequestBodyMiddleware

database:
  default: simplex
  connections:
    simplex:
      type: sqlite
      database: '%resources%/db/database.db'
    social:
      type: sqlite
      database: '%resources%/db/social.db'

auth:
  login_field: email
