modules:
  - App\Blog\BlogModule

providers:
  - Simplex\Routing\RoutingServiceProvider
  - Simplex\Database\DatabaseServiceProvider
  - Simplex\Session\SessionServiceProvider
  - Simplex\Renderer\TwigServiceProvider
  - Simplex\DataMapper\DataMapperServiceProvider

twig:
  path: '%resources%/views'
  file_ext: twig
  extensions:
    - Simplex\Routing\Extensions\TwigRouterExtension

middlewares:
  - Simplex\Middleware\TrailingSlashMiddleware
  - Simplex\Middleware\RoutingMiddleware
  - web:
      - Simplex\Session\SessionMiddleware
      #- Simplex\Middleware\TwigSessionMiddleware
  - api: []

database:
  default: sqlite
  connections:
    sqlite:
      type: sqlite
      database: '%resources%/db/database.db'

