env: debug
modules:
  - App\Blog\BlogModule

providers:
  - Simplex\Routing\RoutingServiceProvider
  - Simplex\Database\DatabaseServiceProvider
  - Simplex\Session\SessionServiceProvider
  - Simplex\Renderer\TwigServiceProvider
  - Simplex\DataMapper\DataMapperServiceProvider
  - Simplex\Validation\ValidationServiceProvider

twig:
  path: '%resources%/views'
  file_ext: twig
  extensions:
    - Simplex\Routing\Extensions\TwigRouterExtension

routing:
  strategies:
    web: Simplex\Middleware\WebMiddleware

  middlewares:
    global:
      - Simplex\Middleware\TrailingSlashMiddleware
      - Simplex\Middleware\ErrorHandlerMiddleware
      - Simplex\Middleware\ValidationErrorsMiddleware
      - Simplex\Middleware\RoutingMiddleware
    web:
      - Simplex\Session\SessionMiddleware
      - Simplex\Middleware\ErrorHandlerMiddleware
      - Simplex\Middleware\TwigSessionMiddleware
    api: []

database:
  default: sqlite
  connections:
    sqlite:
      type: sqlite
      database: '%resources%/db/database.db'

