commands:
  - Simplex\Console\Command\YamlLintCommand
  - Simplex\Console\Command\RouterDebugCommand
  - Simplex\Console\Command\WorkerRunCommand

providers:
  - Simplex\Exception\ExceptionHandlerProvider
  - Simplex\Routing\RoutingServiceProvider
  - Simplex\Database\DatabaseServiceProvider
  - App\Providers\KacheServiceProvider
  - Simplex\Queue\QueueServiceProvider
  - Simplex\Validation\ValidationServiceProvider
  - Simplex\DataMapper\DataMapperServiceProvider
  - Simplex\Security\Authentication\AuthenticationServiceProvider
  - Simplex\Module\ModuleServiceProvider
