twig:
  path: '%resources%/views'
  file_ext: twig
  extensions:
    - Simplex\Routing\Extensions\TwigRouterExtension
    - Simplex\Security\Csrf\TwigCsrfExtension
    - Simplex\Renderer\TwigFormExtension
    - Simplex\Security\Authentication\TwigAuthExtension
