jobeet_home:
  path: /
  controller: App\JobeetModule\Actions\JobShowAction:all

category_show:
  path: /category/{slug}
  controller: App\JobeetModule\Actions\CategoryShowAction:single
  requirements:
    slug: '[a-z0-9-]+'

job_show:
  path: /job/{company}/{location}/{id}/{position}
  controller: App\JobeetModule\Actions\JobShowAction:show
  requirements:
    id: '\d+'

job_new:
  path: /job/new
  controller: App\JobeetModule\Actions\JobEditAction:new
  methods: ['GET']

job_create:
  path: /job/new
  controller: App\JobeetModule\Actions\JobEditAction:create
  methods: ['POST']

job_preview:
  path: /job/{token}
  controller: App\JobeetModule\Actions\JobManageAction:preview
  methods: ['GET']

job_publish:
  path: /job/{token}/publish
  controller: App\JobeetModule\Actions\JobManageAction:publish
  methods: ['GET']

job_edit:
  path: /job/{token}/edit
  controller: App\JobeetModule\Actions\JobEditAction:edit
  methods: ['GET']

job_update:
  path: /job/{token}/edit
  controller: App\JobeetModule\Actions\JobEditAction:update
  methods: ['POST']

job_delete:
  path: /job/{token}/delete
  controller: App\JobeetModule\Actions\JobEditAction:delete
  methods: ['DELETE']